### ISSUE TITLE
messageComponent onPress not triggering

### ISSUE THREAD

**Issue by pierrekarpov** [Qlean/react-native-messages#8]
**Issue Description**

Make a custom View and set onPress prop.
Set messageComponent to be this custom View
When tapping the banner, the action gets trigger only rarely and more consistently on the Simulator than on physical devices.

**Steps to Reproduce / Code Snippets**

```
const BannerComponent = () => {
  return (
    <View style={styles.customMessage} onPress={console.log("Banner pressed!")}>
      <Text style={styles.customMessageText} >Banner Text</Text>
    </View>
  )
}

showMessage(
  {},
  {
    messageComponent: BannerComponent,
    duration: 3000,
    slideAnimationOffset: 200,
    showAnimationDuration: 600,
    hideAnimationDuration: 600,
  },
)
```

**Expected Results**

The onPress function should be called when pressing the element inside the message.

**Suggestion**

Fix in the issue would be nice, but it the meantime, you could add a onPress param to showMessage

**Comment by atiupin** [comment]
@pierrekarpov, thank you for your detailed report. This issue was just fixed in https://github.com/Qlean/react-native-messages/pull/7. Update package to `0.2.4` and then gestures inside notifications should work correctly.

>Fix in the issue would be nice, but it the meantime, you could add a onPress param to showMessage

I suggest you to use custom message components for this. `showMessage` second argument is meant to be a config for `MessageBar`, not for message itself. In any real project default message component will be replaced anyway.
